version: "3"
services:
  mongodb:
    image: mongo:latest
    restart: always
  aoiawd:
    build: .
    depends_on:
      - mongodb
    restart: always
    command: -m mongodb://mongodb:27017
    ports:
      - 1337:1337
      - 8023:8023